# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: p15x
email: phil@p15x.com
description: >
  Knock knock. Race condition. Who's there?
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://p15x.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: "Philippe L'Heureux"
bio: >
  Interested in Machine Learning, Scala, Haskell, Signal Processing and damn good music!

author_image: "/assets/images/author.jpg"
twitter_username: philippelh
github_username:  synhaptein

# Google Analytics
analytics_id: "UA-18895511-1"

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
